### ISSUE TITLE
feature request: beautify *.csv or *.tsv files

### ISSUE THREAD

**Issue by maubarsom** [witchard/mog#17]
Hi,

If at any point you have some time, I think it would be very nice to automatically view formatted files like tables with something like column -xt or so

**Comment by witchard** [comment]
Great idea, I'll add something like this into the default config at some point once I have had a play with what works well. To try it out you can just add this into the ~/.mogrc (somewhere in the middle):

```ini
[columns]
name=.*\.[ct]sv$
arg=column -xt
```

**Comment by maubarsom** [comment]
cool stuff!

On Wed, Feb 15, 2017, 8:45 AM witchard <notifications@github.com> wrote:

Great idea, I'll add something like this into the default config at some
point once I have had a play with what works well. To try it out you can
just add this into the ~/.mogrc (somewhere in the middle):

[columns]
name=.*.[ct]sv$
column -xt

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/witchard/mog/issues/17#issuecomment-279939564>, or mute
the thread
