### ISSUE TITLE
Is pygmentize a dependency?

### ISSUE THREAD

**Issue by danyspin97** [witchard/mog#18]

**Comment by witchard** [comment]
Pygments and pygmentize are used by the pygmentsmime and pygmentize matches. These are used by the default config to do syntax highlighting of source code. However, if you don't use either of those matches in your config file then it should work without pygments installed.

**Comment by danyspin97** [comment]
Can you please change the default config to works out of the box or add the installation of pygmentize in the installation process? So uses won't get errors when running mog after installation.

**Comment by witchard** [comment]
Hmmm it should install pygments and therefore pygmentize as part of the pip install (mog has it marked as a dependency in the setup.py). Looks like this didn't happen for you for some reason... what os are you on?

**Comment by danyspin97** [comment]
The python script installs pygmentize but there is no pygmentize executable in $PATH (which does not contains any python path). I fixed it by installing pygmentize using package manager.
Tried on 2 systems using Arch Linux.

**Comment by witchard** [comment]
Ah interesting... the pygmentize script should be installed to the same place as the mog script to my understanding of what pip does. Therefore if mog is in your $PATH, then pygmentize will also be. I'll try and setup an arch VM and have a play when I get at sec as it works this way when doing it on Debian. How exactly did you do the install so I can try and replicate it?

**Comment by danyspin97** [comment]
`sudo pip install mog`
Without pygmentize installed from pacman i got this error:
`==> Error: "FileNotFoundError(2, "No such file or directory: 'pygmentize'")" when processing file test.sh <==`
My $PATH: `/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl`

**Comment by witchard** [comment]
Strange, so I have just tried this out on arch myself and the pip install process for me does install the pygmentize command correctly. I have updated the install docs to reflect the need for pygmentize however - https://github.com/witchard/mog/commit/f6eb65a2a6eb419615dc79384254d15561e78110.
