### ISSUE TITLE
Archlinux Package

### ISSUE THREAD

**Issue by ghost** [witchard/mog#24]
Just a heads up I created a aur package for mog-git.

https://aur.archlinux.org/packages/mog-git/

**Comment by witchard** [comment]
That's awesome, thank you! Just a note, it also requires the pdftotext utility (from popper-utils) for printing PDF documents. You probably want to put that in the optional dependencies.

**Comment by witchard** [comment]
TODO: add link to arch package in README

**Comment by ghost** [comment]
I think pdftotext is sorted now. Thanks for the heads up.
