### ISSUE TITLE
TypeError when specifying regex which may return empty matches

### ISSUE THREAD

**Issue by x10an14** [witchard/mog#46]
Hi!

With this config in my `~/.mogrc`;
```
[xml]
name=.*(?=(nuget\.config|NuGet\.Config|\.([fc]sproj|ruleset)))
argreplace=pygmentize -l xml -O style=solarized-light %F
```

 I get the following output for files named like the following

- `<folder path>/nuget.config`
- and `<folder path>/NuGet.Config`
(Don't ask my why the mix of capitalization, blame `dotnet core` on Linux =/).

All the while, _**this**_ file matches nicely and displays correctly; `<folder path>/<Project name>.csproj`.

This is the error I get;
```
-> $ mog <failing Nuget xml file>
==> <failing Nuget xml file> <==
==> Error: "TypeError('replace() argument 2 must be str, not None',)" when processing file <failing Nuget xml file> <==
```

**Comment by witchard** [comment]
Can you not just use arg for this instead of argreplace? I.e arg=pygmentize -l xml -O style=solarized-light

**Comment by x10an14** [comment]
Will have to try that!
